---
- hosts: app
  become: true
  tasks:
    - name: Install git
      apt:
        name: git
        state: latest
        update_cache: true

    - name: Clone the Django repository
      git:
        repo: https://github.com/mdn/django-locallibrary-tutorial
        dest: ~/repos
        clone: yes
        update: yes
