---
- hosts: app
  become: true
  tasks:
    - name: Run the Django app in a Docker container
      docker_container:
        name: locallibrary_app
        image: python:3.8-slim
        state: started
        restart_policy: always
        command: |
          bash -c "cd /home/vagrant/django-locallibrary-tutorial && \
          pip install -r requirements.txt && \
          python manage.py migrate && \
          python manage.py runserver 0.0.0.0:8000"
        volumes:
          - /home/vagrant/django-locallibrary-tutorial:/home/vagrant/django-locallibrary-tutorial
        exposed_ports:
          - "8000"
        published_ports:
          - "8000:8000"
        container_default_behavior: compatibility
