---
- hosts: app
  become: true
  tasks:
    - name: List running containers
      command: docker ps
      register: docker_ps_output

    - name: Show running containers
      debug:
        var: docker_ps_output.stdout
